// Расписание группы ИДБ-23-01
// Каждая запись — это конкретное занятие на конкретную дату (не шаблон "по дням недели"),
// рассчитано из семестрового расписания на основе диапазонов дат и типа повторения
// (каждую неделю / через неделю), поэтому лабораторные подгрупп А и Б не дублируются
// на одну и ту же дату — только реальные даты проведения.
const GROUP_NAME = "ИДБ-23-01";

const TIMES = [
  "8:30 – 10:05",
  "10:15 – 11:50",
  "12:20 – 13:55",
  "14:05 – 15:40",
  "15:50 – 17:25",
  "18:00 – 19:30",
  "19:40 – 21:10",
  "21:20 – 22:50",
];

// type: "Лекция" | "Семинар" | "Лабораторная"
// subgroup: "А" | "Б" | null
const LESSONS = [
  { date: "2026-09-01", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-02", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-03", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-05", slot: 0, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-09-07", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-09-07", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Семинар", subgroup: null, room: "0402" },
  { date: "2026-09-08", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-09", slot: 2, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Сигачева М.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-09-09", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-09", slot: 4, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-09-10", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-12", slot: 0, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-09-14", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-09-14", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Семинар", subgroup: null, room: "0402" },
  { date: "2026-09-15", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-15", slot: 1, subject: "Сети и телекоммуникации", teacher: "Сосенушкин С.Е.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-16", slot: 1, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-09-16", slot: 2, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Сигачева М.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-09-16", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-16", slot: 4, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-09-17", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-17", slot: 4, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-09-18", slot: 0, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-09-19", slot: 0, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-09-19", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-09-19", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Семинар", subgroup: null, room: "310" },
  { date: "2026-09-21", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-09-21", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Семинар", subgroup: null, room: "0402" },
  { date: "2026-09-22", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-22", slot: 1, subject: "Сети и телекоммуникации", teacher: "Сосенушкин С.Е.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-23", slot: 1, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-09-23", slot: 2, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Сигачева М.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-09-23", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-23", slot: 4, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-09-24", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-24", slot: 4, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-09-25", slot: 0, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-09-26", slot: 0, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-09-26", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-09-26", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Семинар", subgroup: null, room: "310" },
  { date: "2026-09-28", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-09-28", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Семинар", subgroup: null, room: "0402" },
  { date: "2026-09-29", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-29", slot: 1, subject: "Сети и телекоммуникации", teacher: "Сосенушкин С.Е.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-29", slot: 2, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-30", slot: 1, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-09-30", slot: 2, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Сигачева М.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-09-30", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-09-30", slot: 4, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-01", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-01", slot: 4, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-10-02", slot: 0, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-10-03", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-10-03", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Семинар", subgroup: null, room: "310" },
  { date: "2026-10-05", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-10-05", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Семинар", subgroup: null, room: "0402" },
  { date: "2026-10-06", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-06", slot: 1, subject: "Сети и телекоммуникации", teacher: "Сосенушкин С.Е.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-06", slot: 2, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-07", slot: 1, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-07", slot: 2, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Сигачева М.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-07", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-07", slot: 4, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-08", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-08", slot: 4, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-10-09", slot: 0, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-10-10", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-10-10", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Семинар", subgroup: null, room: "310" },
  { date: "2026-10-12", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-10-12", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Семинар", subgroup: null, room: "0402" },
  { date: "2026-10-13", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-13", slot: 1, subject: "Сети и телекоммуникации", teacher: "Сосенушкин С.Е.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-13", slot: 2, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-14", slot: 2, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Сигачева М.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-14", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-14", slot: 4, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-14", slot: 5, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-15", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-15", slot: 4, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-10-16", slot: 0, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-10-16", slot: 0, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Лабораторная", subgroup: "Б", room: "247" },
  { date: "2026-10-17", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-10-17", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Семинар", subgroup: null, room: "310" },
  { date: "2026-10-19", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-10-19", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-10-20", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-20", slot: 1, subject: "Сети и телекоммуникации", teacher: "Сосенушкин С.Е.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-20", slot: 2, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-21", slot: 2, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Сигачева М.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-21", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-21", slot: 4, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-21", slot: 5, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-22", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-22", slot: 4, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-10-22", slot: 4, subject: "Стратегии развития ИТ бизнеса", teacher: "Тагаев А.И.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-10-23", slot: 0, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-10-23", slot: 0, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Лабораторная", subgroup: "А", room: "247" },
  { date: "2026-10-24", slot: 0, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-10-24", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-10-24", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Семинар", subgroup: null, room: "310" },
  { date: "2026-10-26", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-10-26", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-10-27", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-27", slot: 1, subject: "Сети и телекоммуникации", teacher: "Сосенушкин С.Е.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-27", slot: 2, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-28", slot: 2, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Сигачева М.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-28", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-28", slot: 4, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-28", slot: 5, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-10-29", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-10-29", slot: 4, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-10-29", slot: 4, subject: "Стратегии развития ИТ бизнеса", teacher: "Тагаев А.И.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-10-30", slot: 0, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-10-30", slot: 0, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Лабораторная", subgroup: "Б", room: "247" },
  { date: "2026-10-31", slot: 0, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-10-31", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-10-31", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-10-31", slot: 4, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-11-02", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-11-02", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-11-03", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-03", slot: 1, subject: "Сети и телекоммуникации", teacher: "Сосенушкин С.Е.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-03", slot: 2, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-05", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-05", slot: 4, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-11-05", slot: 4, subject: "Стратегии развития ИТ бизнеса", teacher: "Тагаев А.И.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-11-06", slot: 0, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-11-06", slot: 0, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Лабораторная", subgroup: "А", room: "247" },
  { date: "2026-11-07", slot: 0, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-11-07", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-11-07", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-11-07", slot: 4, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-11-09", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-11-09", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-11-10", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-10", slot: 1, subject: "Сети и телекоммуникации", teacher: "Сосенушкин С.Е.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-10", slot: 2, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-11", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-11", slot: 4, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-11-11", slot: 5, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-11-12", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-12", slot: 4, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-11-12", slot: 4, subject: "Стратегии развития ИТ бизнеса", teacher: "Тагаев А.И.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-11-13", slot: 0, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Лабораторная", subgroup: "Б", room: "247" },
  { date: "2026-11-14", slot: 0, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-11-14", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-11-14", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-11-14", slot: 4, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-11-16", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-11-16", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-11-17", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-17", slot: 1, subject: "Сети и телекоммуникации", teacher: "Сосенушкин С.Е.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-17", slot: 2, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-18", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-18", slot: 4, subject: "Основы новых информационных технологий", teacher: "Ахунов Т.Е.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-11-18", slot: 5, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-11-19", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-19", slot: 4, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-11-19", slot: 4, subject: "Стратегии развития ИТ бизнеса", teacher: "Тагаев А.И.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-11-20", slot: 0, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Лабораторная", subgroup: "А", room: "247" },
  { date: "2026-11-21", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-11-21", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-11-21", slot: 4, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-11-23", slot: 3, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лекция", subgroup: null, room: "0206" },
  { date: "2026-11-23", slot: 4, subject: "Системы искусственного интеллекта", teacher: "Стоякова К.Л.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-11-24", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-24", slot: 2, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-25", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-25", slot: 5, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Семинар", subgroup: null, room: "—" },
  { date: "2026-11-26", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-11-26", slot: 4, subject: "Стратегии развития ИТ бизнеса", teacher: "Тагаев А.И.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-11-27", slot: 0, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Лабораторная", subgroup: "Б", room: "247" },
  { date: "2026-11-28", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-11-28", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-11-28", slot: 4, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-12-01", slot: 0, subject: "Основы новых информационных технологий", teacher: "Бибиков О.Д.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-12-01", slot: 2, subject: "Стратегии развития ИТ бизнеса", teacher: "Александров С.А.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-12-02", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-12-03", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-12-03", slot: 4, subject: "Стратегии развития ИТ бизнеса", teacher: "Тагаев А.И.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-12-04", slot: 0, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Лабораторная", subgroup: "А", room: "247" },
  { date: "2026-12-05", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-12-05", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-12-05", slot: 4, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лабораторная", subgroup: "А", room: "—" },
  { date: "2026-12-09", slot: 3, subject: "Защита информации", teacher: "Симонов М.Ф.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-12-10", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-12-10", slot: 4, subject: "Стратегии развития ИТ бизнеса", teacher: "Тагаев А.И.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-12-11", slot: 0, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Лабораторная", subgroup: "Б", room: "247" },
  { date: "2026-12-12", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-12-12", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лабораторная", subgroup: "А", room: "240(а)" },
  { date: "2026-12-12", slot: 4, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лабораторная", subgroup: "Б", room: "—" },
  { date: "2026-12-17", slot: 3, subject: "Стандартизация и нормативное регулирование цифровых систем", teacher: "Бабенко Е.В.", type: "Лекция", subgroup: null, room: "—" },
  { date: "2026-12-18", slot: 0, subject: "Сети и телекоммуникации", teacher: "Казовский М.Д.", type: "Лабораторная", subgroup: "А", room: "247" },
  { date: "2026-12-19", slot: 1, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лекция", subgroup: null, room: "0411" },
  { date: "2026-12-19", slot: 2, subject: "Современные технологии и средства разработки ПО", teacher: "Гаврилов А.Г.", type: "Лабораторная", subgroup: "Б", room: "240(а)" },
  { date: "2026-12-19", slot: 4, subject: "Операционные системы", teacher: "Пушкин А.Ю.", type: "Лабораторная", subgroup: "А", room: "—" },
];
